In [1]:
%matplotlib inline

import tqdm
import os 
import glob 
import sys
sys.path.append('/home/ngr4/project/edge_feat/scripts')
import pickle
import torch
import torch.nn as nn
import torch.nn.functional as F
# import utils
# import load_data as data
import math
import numpy as np
import pandas as pd
import seaborn as sns
from torch_geometric.nn import GCNConv
import matplotlib.pyplot as plt
from scipy.sparse import coo_matrix
# import graphtools as gt
# import phate
# import umap

from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
import scanpy as sc
from scipy import sparse
# import scprep
import time
import datetime
from scipy.stats import zscore
from adjustText import adjust_text


from sklearn.linear_model import LogisticRegression
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import train_test_split

from captum.attr import (
#     GradientShap,
#     DeepLift,
#     DeepLiftShap,
    IntegratedGradients,
#     LayerConductance,
#     NeuronConductance,
    NoiseTunnel,
)



plt.rc('font', size = 8)
plt.rc('font', family='sans serif')
plt.rcParams['pdf.fonttype']=42
plt.rcParams['ps.fonttype']=42
plt.rcParams['legend.frameon']=False
sns.set_style("ticks")

/home/nravindra/miniconda3/envs/scnd2/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import sys
sys.path.append('/home/nravindra/project/')
from scnd.scripts import scgat_pipeline_dev as scgat

In [6]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_5wk --datekey 221012_122944 --eval_split test



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  8.09it/s]

Test set eval:
  <loss>mb: 0.1502
  <acc >mb: 0.9420

SCA1_5wk results
-----------------------
Accuracy      : 0.8472
Sensitivity   : 0.8235
Specificity   : 0.8506

Ave. precision: 0.3537
Precision     : 0.9369
Recall        : 1.0000

AU-ROC        : 0.9046
AU-PRC        : 0.3616
Brier         : 0.0468
F1            : 0.3803

Confusion matrix: (i-th truth, j-th pred)
[[461  81]
 [  7  27]]


In [7]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_12wk --datekey 221012_130920 --eval_split test



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.37it/s]

Test set eval:
  <loss>mb: 0.1344
  <acc >mb: 0.9506

SCA1_12wk results
-----------------------
Accuracy      : 0.9021
Sensitivity   : 0.9474
Specificity   : 0.9007

Ave. precision: 0.5865
Precision     : 0.9283
Recall        : 1.0000

AU-ROC        : 0.9595
AU-PRC        : 0.5783
Brier         : 0.0424
F1            : 0.5556

Confusion matrix: (i-th truth, j-th pred)
[[481  53]
 [  3  35]]


In [8]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_18wk --datekey 221012_130946 --eval_split test



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.54it/s]

Test set eval:
  <loss>mb: 0.2544
  <acc >mb: 0.8896

SCA1_18wk results
-----------------------
Accuracy      : 0.8675
Sensitivity   : 0.9634
Specificity   : 0.8537

Ave. precision: 0.6886
Precision     : 0.8395
Recall        : 1.0000

AU-ROC        : 0.9494
AU-PRC        : 0.6845
Brier         : 0.0713
F1            : 0.6695

Confusion matrix: (i-th truth, j-th pred)
[[426  73]
 [  4  78]]


In [9]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_24wk --datekey 221012_131105 --eval_split test



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.50it/s]

Test set eval:
  <loss>mb: 0.1210
  <acc >mb: 0.9526

SCA1_24wk results
-----------------------
Accuracy      : 0.8895
Sensitivity   : 1.0000
Specificity   : 0.8859

Ave. precision: 0.7497
Precision     : 0.9512
Recall        : 1.0000

AU-ROC        : 0.9817
AU-PRC        : 0.7451
Brier         : 0.0217
F1            : 0.4483

Confusion matrix: (i-th truth, j-th pred)
[[489  63]
 [  1  26]]


In [10]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_30wk --datekey 221012_143843 --eval_split test



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  8.72it/s]

Test set eval:
  <loss>mb: 0.1725
  <acc >mb: 0.9294

SCA1_30wk results
-----------------------
Accuracy      : 0.8752
Sensitivity   : 0.9474
Specificity   : 0.8663

Ave. precision: 0.8185
Precision     : 0.8555
Recall        : 1.0000

AU-ROC        : 0.9544
AU-PRC        : 0.8172
Brier         : 0.0486
F1            : 0.6636

Confusion matrix: (i-th truth, j-th pred)
[[434  67]
 [  5  71]]


In [11]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label ysca1 --datekey 221012_110419 --eval_split test



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.55it/s]

Test set eval:
  <loss>mb: 0.4582
  <acc >mb: 0.7723

ysca1 results
-----------------------
Accuracy      : 0.8028
Sensitivity   : 0.7790
Specificity   : 0.8272

Ave. precision: 0.8685
Precision     : 0.4595
Recall        : 1.0000

AU-ROC        : 0.8769
AU-PRC        : 0.8682
Brier         : 0.1473
F1            : 0.7871

Confusion matrix: (i-th truth, j-th pred)
[[249  52]
 [ 60 207]]


In [12]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label ygenotime --datekey 221012_145251 --eval_split test



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.59it/s]

Test set eval:
  <loss>mb: 1.3807
  <acc >mb: 0.5101
Traceback (most recent call last):
  File "/home/nravindra/project/scnd/scripts/eval_metrics_v22.py", line 113, in <module>
    fpr, tpr, thresholds = metrics.roc_curve(y_true, p1)
  File "/home/nravindra/miniconda3/envs/scnd2/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 981, in roc_curve
    fps, tps, thresholds = _binary_clf_

# try on val set

In [13]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_5wk --datekey 221012_122944 --eval_split val



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.91it/s]

Test set eval:
  <loss>mb: 0.1488
  <acc >mb: 0.9433

SCA1_5wk results
-----------------------
Accuracy      : 0.8633
Sensitivity   : 0.9500
Specificity   : 0.8587

Ave. precision: 0.5665
Precision     : 0.9244
Recall        : 1.0000

AU-ROC        : 0.9429
AU-PRC        : 0.5590
Brier         : 0.0408
F1            : 0.4837

Confusion matrix: (i-th truth, j-th pred)
[[462  76]
 [  3  37]]


In [14]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_12wk --datekey 221012_130920 --eval_split val



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.29it/s]

Test set eval:
  <loss>mb: 0.1374
  <acc >mb: 0.9501

SCA1_12wk results
-----------------------
Accuracy      : 0.8813
Sensitivity   : 0.9111
Specificity   : 0.8807

Ave. precision: 0.5847
Precision     : 0.9148
Recall        : 1.0000

AU-ROC        : 0.9448
AU-PRC        : 0.5774
Brier         : 0.0473
F1            : 0.5405

Confusion matrix: (i-th truth, j-th pred)
[[465  63]
 [  5  40]]


In [15]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_18wk --datekey 221012_130946 --eval_split val



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  8.05it/s]

Test set eval:
  <loss>mb: 0.2722
  <acc >mb: 0.8835

SCA1_18wk results
-----------------------
Accuracy      : 0.8599
Sensitivity   : 0.9667
Specificity   : 0.8341

Ave. precision: 0.8128
Precision     : 0.7600
Recall        : 1.0000

AU-ROC        : 0.9525
AU-PRC        : 0.8118
Brier         : 0.0832
F1            : 0.7395

Confusion matrix: (i-th truth, j-th pred)
[[382  76]
 [  5 115]]


In [16]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_24wk --datekey 221012_131105 --eval_split val


 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.55it/s]

Test set eval:
  <loss>mb: 0.1234
  <acc >mb: 0.9481

SCA1_24wk results
-----------------------
Accuracy      : 0.9284
Sensitivity   : 0.8684
Specificity   : 0.9346

Ave. precision: 0.6451
Precision     : 0.9305
Recall        : 1.0000

AU-ROC        : 0.9562
AU-PRC        : 0.6438
Brier         : 0.0462
F1            : 0.6095

Confusion matrix: (i-th truth, j-th pred)
[[500  35]
 [  6  32]]


In [17]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label SCA1_30wk --datekey 221012_143843 --eval_split val



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  8.64it/s]

Test set eval:
  <loss>mb: 0.1728
  <acc >mb: 0.9284

SCA1_30wk results
-----------------------
Accuracy      : 0.9017
Sensitivity   : 0.9565
Specificity   : 0.8943

Ave. precision: 0.6837
Precision     : 0.8698
Recall        : 1.0000

AU-ROC        : 0.9571
AU-PRC        : 0.6816
Brier         : 0.0566
F1            : 0.6952

Confusion matrix: (i-th truth, j-th pred)
[[458  53]
 [  4  65]]


In [18]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label ysca1 --datekey 221012_110419 --eval_split val



 Starting eval...
/home/nravindra/project/scnd/scripts/scgat_pipeline_dev.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755897462/work/torch/csrc/utils/tensor_new.cpp:210.)
  indices=torch.LongTensor([coo_data.row, coo_data.col]) # OR transpose list of index tuples
Computing METIS partitioning...
Done!
100%|███████████████████████████████████████████| 20/20 [00:02<00:00,  7.56it/s]

Test set eval:
  <loss>mb: 0.4836
  <acc >mb: 0.7512

ysca1 results
-----------------------
Accuracy      : 0.7778
Sensitivity   : 0.7439
Specificity   : 0.8153

Ave. precision: 0.8609
Precision     : 0.4148
Recall        : 0.9862

AU-ROC        : 0.8633
AU-PRC        : 0.8606
Brier         : 0.1638
F1            : 0.7698

Confusion matrix: (i-th truth, j-th pred)
[[234  53]
 [ 75 214]]


In [ ]:
!python -u /home/nravindra/project/scnd/scripts/eval_metrics_v22.py --label ygenotime --datekey 221012_110419 --eval_split val
